Algoritmo "Verificação de número par ou ímpar"
//
//
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : João Bogo
// Data atual  : 16/03/2023
Var
   // Seção de Declarações das variáveis
   n1 :inteiro
Inicio
   escreva( " Digite um número inteiro " )
   leia (n1)
   se (n1 mod 2)= 0 entao
      escreva ( " Seu número é par " )
      senao
      escreva ( " Seu número é ímpar " )
   fimse



Fimalgoritmo